# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Add_Field
                                 A QGIS plugin
 ffff
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-03-20
        copyright            : (C) 2021 by Kalina Juszczyk
        email                : kalina.juszczyk@wp.pl
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Add_Field class from file Add_Field.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Add_Field import Add_Field
    return Add_Field(iface)
